import { PrismaClient, type Artist } from "@prisma/client";
import { INDEXES, removeFromIndex, searchClient } from "../src/lib/meilisearch";

type ArtistWithCounts = Artist & {
  _count: {
    music: number;
    albums: number;
    artistFollows: number;
  };
};

type GroupPlan = {
  key: string;
  targetName: string;
  canonicalId: string;
  canonicalName: string;
  memberIds: string[];
  duplicateIds: string[];
  mergeCount: number;
};

type RenamePlan = {
  artistId: string;
  fromName: string;
  toName: string;
  toSlug: string;
};

type CleanupReport = {
  totalArtists: number;
  mergeGroups: GroupPlan[];
  renamePlans: RenamePlan[];
  skippedAmbiguous: Array<{
    id: string;
    name: string;
    reason: string;
    suggestedBase: string | null;
  }>;
};

const db = new PrismaClient();
const shouldApply = process.argv.includes("--apply") || process.env.APPLY_ARTIST_CLEANUP === "1";
const PREFERRED_NAME_OVERRIDES: Record<string, string> = {
  asa: "Asa",
  isec: "iSEC",
};

function canonicalKey(value: string): string {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[’'`]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "");
}

function collapseWhitespace(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

function sanitizeDisplayName(value: string): string {
  return collapseWhitespace(
    value
      .replace(/\u00a0/g, " ")
      .replace(/[\r\n\t]+/g, " ")
      .trim()
  );
}

function slugify(value: string): string {
  return sanitizeDisplayName(value)
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[’'`]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function looksAutoGeneratedSlug(slug: string): boolean {
  return /-[a-z0-9]{6,12}$/i.test(slug);
}

function stripTrailingSource(name: string): string {
  return name
    .replace(/\|\|.*$/i, "")
    .replace(/\s+-\s*(tooxclusive|naijaloaded|thenetng|themidemedia)\b.*$/i, "")
    .replace(/\b[a-z0-9.-]+\.(com|net|ng|org|co)\b.*$/i, "")
    .trim();
}

function stripFeaturedSegments(name: string): string {
  return stripTrailingSource(name)
    .replace(/\s*\((feat\.?|ft\.?|featuring)[^)]+\)/gi, "")
    .split(/\s+(?:feat\.?|ft\.?|featuring)\s+/i)[0]
    .split(/\s+[xX]\s+/)[0]
    .trim();
}

function extractPrimaryArtistName(name: string): string | null {
  const cleaned = stripFeaturedSegments(name);
  const normalized = sanitizeDisplayName(cleaned);
  return normalized.length > 0 ? normalized : null;
}

function isSuspiciousName(name: string): boolean {
  const lowered = name.toLowerCase();
  return (
    lowered.includes("||") ||
    /\bfeat(?:uring)?\.?\b/.test(lowered) ||
    /\bft\.?\b/.test(lowered) ||
    /\s+[x]\s+/.test(lowered) ||
    /\b[a-z0-9.-]+\.(com|net|ng|org|co)\b/.test(lowered)
  );
}

function isPlaceholderArtist(name: string): boolean {
  const normalized = canonicalKey(name);
  return ["unknown", "untitled", "variousartists"].includes(normalized);
}

function isMostlyUppercase(name: string): boolean {
  const letters = name.replace(/[^A-Za-z]/g, "");
  return letters.length > 3 && letters === letters.toUpperCase();
}

function displayNameScore(name: string): number {
  let score = 0;

  if (!isSuspiciousName(name)) score += 30;
  if (!isMostlyUppercase(name)) score += 10;
  if (!/[”“"]/u.test(name)) score += 10;
  if (!/\s{2,}/.test(name)) score += 8;
  if (!/^\s|\s$/u.test(name)) score += 8;
  if (!/[|]/.test(name)) score += 8;

  score -= name.length * 0.1;

  return score;
}

function fieldScore(artist: ArtistWithCounts, targetName: string): number {
  const expectedSlug = slugify(targetName);
  let score = 0;

  if (artist.slug === expectedSlug) score += 150;
  if (!looksAutoGeneratedSlug(artist.slug)) score += 40;
  if (sanitizeDisplayName(artist.name) === targetName) score += 25;
  if (!isSuspiciousName(artist.name)) score += 20;
  if (artist.bio) score += 35;
  if (artist.photo) score += 20;
  if (artist.coverImage) score += 20;
  if (artist.verified) score += 15;
  if (artist.instagram) score += 5;
  if (artist.twitter) score += 5;
  if (artist.facebook) score += 5;
  if (artist.spotify) score += 5;
  if (artist.appleMusic) score += 5;

  score += artist._count.music * 3;
  score += artist._count.albums * 4;
  score += artist._count.artistFollows * 2;

  return score;
}

function choosePreferredTargetName(group: ArtistWithCounts[]): string {
  const candidates = new Map<string, number>();

  for (const artist of group) {
    const candidate = extractPrimaryArtistName(sanitizeDisplayName(artist.name));
    if (!candidate) continue;

    const score = displayNameScore(candidate) + fieldScore(artist, candidate);
    const current = candidates.get(candidate) ?? Number.NEGATIVE_INFINITY;
    if (score > current) {
      candidates.set(candidate, score);
    }
  }

  const fallback =
    [...candidates.entries()].sort((left, right) => right[1] - left[1])[0]?.[0] ??
    sanitizeDisplayName(group[0].name);
  return PREFERRED_NAME_OVERRIDES[canonicalKey(fallback)] ?? fallback;
}

function chooseCanonical(group: ArtistWithCounts[], targetName: string): ArtistWithCounts {
  return [...group].sort((left, right) => {
    const scoreDiff = fieldScore(right, targetName) - fieldScore(left, targetName);
    if (scoreDiff !== 0) return scoreDiff;

    const leftName = sanitizeDisplayName(left.name);
    const rightName = sanitizeDisplayName(right.name);
    const leftExpected = leftName === targetName ? 1 : 0;
    const rightExpected = rightName === targetName ? 1 : 0;
    if (rightExpected !== leftExpected) return rightExpected - leftExpected;

    return left.createdAt.getTime() - right.createdAt.getTime();
  })[0];
}

function mergeArtistData(
  canonical: ArtistWithCounts,
  duplicates: ArtistWithCounts[],
  targetName: string
) {
  const merged: Partial<Artist> = {
    name:
      sanitizeDisplayName(canonical.name) === targetName || isSuspiciousName(canonical.name)
        ? targetName
        : sanitizeDisplayName(canonical.name),
  };

  const fieldNames: Array<keyof Artist> = [
    "bio",
    "photo",
    "coverImage",
    "country",
    "genre",
    "instagram",
    "twitter",
    "facebook",
    "spotify",
    "appleMusic",
    "ownerId",
    "labelId",
  ];

  for (const field of fieldNames) {
    if (canonical[field]) continue;
    const donor = duplicates.find((artist) => artist[field]);
    if (donor) merged[field] = donor[field] as never;
  }

  if (!canonical.verified) {
    merged.verified = duplicates.some((artist) => artist.verified) || canonical.verified;
  }

  return merged;
}

async function transferArtistFollows(fromArtistId: string, toArtistId: string): Promise<void> {
  const follows = await db.artistFollow.findMany({
    where: { artistId: fromArtistId },
    select: { userId: true },
  });

  for (const follow of follows) {
    await db.artistFollow.upsert({
      where: {
        userId_artistId: {
          userId: follow.userId,
          artistId: toArtistId,
        },
      },
      update: {},
      create: {
        userId: follow.userId,
        artistId: toArtistId,
      },
    });
  }

  await db.artistFollow.deleteMany({ where: { artistId: fromArtistId } });
}

function buildCleanupReport(artists: ArtistWithCounts[]): CleanupReport {
  const byTargetKey = new Map<string, ArtistWithCounts[]>();

  for (const artist of artists) {
    const cleanedName = sanitizeDisplayName(artist.name);
    const targetName = extractPrimaryArtistName(cleanedName) ?? cleanedName;
    const targetKey = canonicalKey(targetName);
    if (!targetKey) continue;

    const group = byTargetKey.get(targetKey) ?? [];
    group.push(artist);
    byTargetKey.set(targetKey, group);
  }

  const mergeGroups: GroupPlan[] = [];
  const renamePlans: RenamePlan[] = [];
  const skippedAmbiguous: CleanupReport["skippedAmbiguous"] = [];

  for (const group of byTargetKey.values()) {
    const targetName = choosePreferredTargetName(group);
    const targetKey = canonicalKey(targetName);
    const hasSuspiciousMember = group.some((artist) => isSuspiciousName(artist.name));

    if (group.length > 1 || hasSuspiciousMember) {
      const canonical = chooseCanonical(group, targetName);
      const duplicateIds = group
        .filter((artist) => artist.id !== canonical.id)
        .map((artist) => artist.id);
      if (duplicateIds.length > 0) {
        mergeGroups.push({
          key: targetKey,
          targetName,
          canonicalId: canonical.id,
          canonicalName: canonical.name,
          memberIds: group.map((artist) => artist.id),
          duplicateIds,
          mergeCount: duplicateIds.length,
        });
        continue;
      }
    }

    const artist = group[0];
    const cleanedCurrentName = sanitizeDisplayName(artist.name);
    const primaryName = extractPrimaryArtistName(cleanedCurrentName);

    if (targetName !== cleanedCurrentName && !isPlaceholderArtist(cleanedCurrentName)) {
      renamePlans.push({
        artistId: artist.id,
        fromName: cleanedCurrentName,
        toName: targetName,
        toSlug: slugify(targetName),
      });
      continue;
    }

    if (isPlaceholderArtist(cleanedCurrentName)) {
      skippedAmbiguous.push({
        id: artist.id,
        name: cleanedCurrentName,
        reason: "placeholder-artist",
        suggestedBase: null,
      });
      continue;
    }

    if (cleanedCurrentName !== artist.name) {
      renamePlans.push({
        artistId: artist.id,
        fromName: artist.name,
        toName: cleanedCurrentName,
        toSlug: artist.slug,
      });
      continue;
    }

    if (isSuspiciousName(cleanedCurrentName) && !primaryName) {
      skippedAmbiguous.push({
        id: artist.id,
        name: cleanedCurrentName,
        reason: "could-not-derive-primary-name",
        suggestedBase: null,
      });
    }
  }

  // Skip rename plans that would collide with merge targets or existing canonical names.
  const mergedKeys = new Set(mergeGroups.map((group) => group.key));
  const filteredRenamePlans = renamePlans.filter(
    (plan) => !mergedKeys.has(canonicalKey(plan.toName))
  );

  return {
    totalArtists: artists.length,
    mergeGroups,
    renamePlans: filteredRenamePlans,
    skippedAmbiguous,
  };
}

async function refreshArtistSearchIndex(touchedCanonicalIds: string[], removedArtistIds: string[]) {
  for (const artistId of removedArtistIds) {
    removeFromIndex(INDEXES.ARTISTS, artistId);
  }

  if (touchedCanonicalIds.length === 0) return;

  const artists = await db.artist.findMany({
    where: { id: { in: [...new Set(touchedCanonicalIds)] } },
    select: {
      id: true,
      slug: true,
      name: true,
      genre: true,
      photo: true,
      bio: true,
    },
  });

  if (artists.length === 0) return;

  await searchClient
    .index(INDEXES.ARTISTS)
    .addDocuments(
      artists.map((artist) => ({
        id: artist.id,
        slug: artist.slug,
        name: artist.name,
        genre: artist.genre ?? null,
        photo: artist.photo ?? null,
        bio: artist.bio ? artist.bio.slice(0, 300) : null,
      }))
    )
    .catch(() => {});
}

async function applyCleanup(report: CleanupReport, artistsById: Map<string, ArtistWithCounts>) {
  const touchedCanonicalIds: string[] = [];
  const removedArtistIds: string[] = [];

  for (const groupPlan of report.mergeGroups) {
    const groupArtists = groupPlan.memberIds
      .map((id) => artistsById.get(id))
      .filter((artist): artist is ArtistWithCounts => Boolean(artist));

    const canonical = groupArtists.find((artist) => artist.id === groupPlan.canonicalId);
    if (!canonical) continue;

    const duplicates = groupArtists.filter((artist) => artist.id !== canonical.id);
    const mergedData = mergeArtistData(canonical, duplicates, groupPlan.targetName);

    await db.$transaction(async (tx) => {
      if (Object.keys(mergedData).length > 0) {
        const nextSlug = slugify(groupPlan.targetName);
        if (nextSlug && !looksAutoGeneratedSlug(canonical.slug) && canonical.slug !== nextSlug) {
          const conflictingArtist = await tx.artist.findFirst({
            where: { slug: nextSlug, id: { not: canonical.id } },
            select: { id: true },
          });
          if (!conflictingArtist) {
            mergedData.slug = nextSlug;
          }
        }

        await tx.artist.update({
          where: { id: canonical.id },
          data: mergedData,
        });
      }

      for (const duplicate of duplicates) {
        await tx.music.updateMany({
          where: { artistId: duplicate.id },
          data: { artistId: canonical.id },
        });
        await tx.album.updateMany({
          where: { artistId: duplicate.id },
          data: { artistId: canonical.id },
        });
      }
    });

    for (const duplicate of duplicates) {
      await transferArtistFollows(duplicate.id, canonical.id);
      await db.artist.delete({ where: { id: duplicate.id } });
      removedArtistIds.push(duplicate.id);
    }

    touchedCanonicalIds.push(canonical.id);
  }

  for (const rename of report.renamePlans) {
    const current = artistsById.get(rename.artistId);
    if (!current) continue;

    const updateData: { name: string; slug?: string } = { name: rename.toName };

    if (rename.toSlug && rename.toSlug !== current.slug) {
      const conflictingArtist = await db.artist.findFirst({
        where: {
          slug: rename.toSlug,
          id: { not: rename.artistId },
        },
        select: { id: true },
      });
      if (!conflictingArtist) {
        updateData.slug = rename.toSlug;
      }
    }

    await db.artist.update({
      where: { id: rename.artistId },
      data: updateData,
    });

    touchedCanonicalIds.push(rename.artistId);
  }

  await refreshArtistSearchIndex(touchedCanonicalIds, removedArtistIds);
}

async function main() {
  const artists = await db.artist.findMany({
    include: {
      _count: {
        select: {
          music: true,
          albums: true,
          artistFollows: true,
        },
      },
    },
    orderBy: { name: "asc" },
  });

  const report = buildCleanupReport(artists);

  console.log(
    JSON.stringify(
      {
        mode: shouldApply ? "apply" : "dry-run",
        totalArtists: report.totalArtists,
        mergeGroups: report.mergeGroups.length,
        artistsToMerge: report.mergeGroups.reduce((sum, group) => sum + group.mergeCount, 0),
        renamePlans: report.renamePlans.length,
        skippedAmbiguous: report.skippedAmbiguous.length,
        sampleMergeGroups: report.mergeGroups.slice(0, 25),
        sampleRenamePlans: report.renamePlans.slice(0, 25),
        sampleSkipped: report.skippedAmbiguous.slice(0, 25),
      },
      null,
      2
    )
  );

  if (!shouldApply) return;

  const artistsById = new Map(artists.map((artist) => [artist.id, artist]));
  await applyCleanup(report, artistsById);
}

main()
  .catch((error) => {
    console.error("[cleanup-artists]", error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await db.$disconnect();
  });
