-- CreateTable
CREATE TABLE "SiteSettings" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "siteName" TEXT NOT NULL DEFAULT 'Soundloaded Blog',
    "tagline" TEXT NOT NULL DEFAULT 'Nigeria''s #1 music download & entertainment blog',
    "siteUrl" TEXT NOT NULL DEFAULT 'https://soundloadedblog.ng',
    "contactEmail" TEXT NOT NULL DEFAULT '',
    "copyrightText" TEXT NOT NULL DEFAULT 'Soundloaded Nigeria. All rights reserved.',
    "logoLight" TEXT,
    "logoDark" TEXT,
    "favicon" TEXT,
    "defaultOgImage" TEXT,
    "metaTitleTemplate" TEXT NOT NULL DEFAULT '%s | Soundloaded Blog',
    "metaDescription" TEXT NOT NULL DEFAULT 'Nigeria''s premier music blog — latest music news, free music downloads, gist, artist profiles, and more.',
    "googleSiteVerification" TEXT NOT NULL DEFAULT '',
    "bingSiteVerification" TEXT NOT NULL DEFAULT '',
    "googleAnalyticsId" TEXT NOT NULL DEFAULT '',
    "seoKeywords" TEXT NOT NULL DEFAULT 'Nigeria music, Afrobeats, free music download, music news, African music',
    "instagram" TEXT NOT NULL DEFAULT 'soundloadedng',
    "twitter" TEXT NOT NULL DEFAULT 'soundloadedng',
    "facebook" TEXT NOT NULL DEFAULT 'soundloadedng',
    "youtube" TEXT NOT NULL DEFAULT '',
    "spotify" TEXT NOT NULL DEFAULT '',
    "tiktok" TEXT NOT NULL DEFAULT '',
    "appleMusic" TEXT NOT NULL DEFAULT '',
    "telegram" TEXT NOT NULL DEFAULT '',
    "whatsapp" TEXT NOT NULL DEFAULT '',
    "pwaAppName" TEXT NOT NULL DEFAULT 'Soundloaded Blog',
    "pwaShortName" TEXT NOT NULL DEFAULT 'Soundloaded',
    "pwaThemeColor" TEXT NOT NULL DEFAULT '#e11d48',
    "pwaBackgroundColor" TEXT NOT NULL DEFAULT '#0a0a0a',
    "pwaDisplayMode" TEXT NOT NULL DEFAULT 'standalone',
    "pwaOrientation" TEXT NOT NULL DEFAULT 'any',
    "pwaIcons" JSONB NOT NULL DEFAULT '[]',
    "pwaSplashScreens" JSONB NOT NULL DEFAULT '[]',
    "discordWebhookUrl" TEXT NOT NULL DEFAULT '',
    "notifyOnNewComment" BOOLEAN NOT NULL DEFAULT true,
    "notifyOnNewSubscriber" BOOLEAN NOT NULL DEFAULT true,
    "notifyOnNewMusicUpload" BOOLEAN NOT NULL DEFAULT false,
    "emailNotificationsAdmin" BOOLEAN NOT NULL DEFAULT true,
    "postsPerPage" INTEGER NOT NULL DEFAULT 20,
    "enableComments" BOOLEAN NOT NULL DEFAULT true,
    "autoApproveComments" BOOLEAN NOT NULL DEFAULT false,
    "defaultPostStatus" TEXT NOT NULL DEFAULT 'DRAFT',
    "enableDownloads" BOOLEAN NOT NULL DEFAULT true,
    "maxDownloadsPerHour" INTEGER NOT NULL DEFAULT 10,
    "brandColor" TEXT NOT NULL DEFAULT '#e11d48',
    "enableDarkMode" BOOLEAN NOT NULL DEFAULT true,
    "defaultTheme" TEXT NOT NULL DEFAULT 'dark',
    "customCss" TEXT NOT NULL DEFAULT '',

    CONSTRAINT "SiteSettings_pkey" PRIMARY KEY ("id")
);
