-- AlterTable
ALTER TABLE "SiteSettings" ADD COLUMN     "allowRegistration" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "closeCommentsAfterDays" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "commentBlocklist" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "commentModerationKeywords" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "commentNestingDepth" INTEGER NOT NULL DEFAULT 2,
ADD COLUMN     "commentOrder" TEXT NOT NULL DEFAULT 'oldest',
ADD COLUMN     "commentsPerPage" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN     "dateFormat" TEXT NOT NULL DEFAULT 'MMM d, yyyy',
ADD COLUMN     "defaultUserRole" TEXT NOT NULL DEFAULT 'READER',
ADD COLUMN     "emailDigestDay" TEXT NOT NULL DEFAULT 'monday',
ADD COLUMN     "emailDigestEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "emailFromAddress" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "emailFromName" TEXT NOT NULL DEFAULT 'Soundloaded Blog',
ADD COLUMN     "emailWelcomeEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "enableWatermark" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "feedContentMode" TEXT NOT NULL DEFAULT 'excerpt',
ADD COLUMN     "feedItemCount" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN     "footerScripts" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "headerScripts" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "imageQuality" INTEGER NOT NULL DEFAULT 80,
ADD COLUMN     "language" TEXT NOT NULL DEFAULT 'en',
ADD COLUMN     "largeImageSize" INTEGER NOT NULL DEFAULT 1200,
ADD COLUMN     "loginLockoutDuration" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN     "maintenanceAllowedIPs" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "maintenanceMessage" TEXT NOT NULL DEFAULT 'We''re upgrading. Be right back!',
ADD COLUMN     "maintenanceMode" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "maxLoginAttempts" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "mediumImageSize" INTEGER NOT NULL DEFAULT 600,
ADD COLUMN     "requireLoginToComment" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "requireStrongPasswords" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "searchEngineVisibility" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "thumbnailSize" INTEGER NOT NULL DEFAULT 150,
ADD COLUMN     "timeFormat" TEXT NOT NULL DEFAULT 'h:mm a',
ADD COLUMN     "timezone" TEXT NOT NULL DEFAULT 'Africa/Lagos',
ADD COLUMN     "watermarkImage" TEXT,
ADD COLUMN     "watermarkPosition" TEXT NOT NULL DEFAULT 'bottom-right';
